### ISSUE TITLE
About the mean_variance_norm function

### ISSUE THREAD

**Issue by o0t1ng0o** [GlebBrykin/SANET#3]
Hi, @GlebBrykin 
Is the mean_variance_norm function the same as the instance normalization?
https://github.com/GlebBrykin/SANET/blob/de67fba8dad8b041031ab0660a4c90471bab408f/Eval.py#L21

**Comment by GlebSBrykin** [comment]
Good day, sorry for the long wait! mean_variance_norm - not quite instance normalization. This is, like, half of that normalization. That is, we give mean to 0 and variation to 1 for the input tensor, but after that we do not multiply and add, as in instance norm, but simply return the tensor.

**Comment by o0t1ng0o** [comment]
Thank you for your reply~~
