### ISSUE TITLE
about the 1X1 convolution after the san

### ISSUE THREAD

**Issue by hello-trouble** [GlebBrykin/SANET#4]
Dear Sir:
         Thank you for your excellent job of 《Arbitrary Style Transfer with Style-Attentional Networks
》，I am puzzled about the 1*1 convolution after the san module:"After applying 1 × 1 convolution to Fcs and summing the two matrices element-wise as follows, we obtain Fcsc”.  Why do you choose to use it here ?Thank you for your help !

**Comment by GlebSBrykin** [comment]
I am not the author of this algorithm, I implemented a neural network as described by Dae Young Park. I think You should ask him that. Personally my opinion: this convolution need a for more soft adding content and stylized images (exit with SANet). I. e. SANet in its pure form gives signs that are very different from those that were at the entrance to the SANet (for example, intensity). Convolution smoothes these effects and allows for a better image.
