### ISSUE TITLE
Is there any Training scripts?

### ISSUE THREAD

**Issue by lzlzlizi** [GlebBrykin/SANET#5]
Thanks for your codes. However, I have a question. Why the iteration step is 1? When I tried to set it, say 100, the result sucks, since only the outcome of step 1 is fine and others are just mixed pieces of style picture and content picture.

And I notice that the original paper says it needs to be trained on coco, so did you implement the training codes?

**Comment by GlebSBrykin** [comment]
Step in Eval.py - this is the number of stylization iterations per image, i.e. it is not network training, but evaluation. The typical value of this parameter is 1, as you noticed, but you can set values up to 5, they in many cases allow you to achieve better results than at 1. Training codes (Train.ipynb) I posted. Trained on Google Colab using the parameters specified in the author's paper.

**Comment by lzlzlizi** [comment]
Thanks a lot!
